### ISSUE TITLE
more examples

### ISSUE THREAD

**Issue by cyrfer** [nordsimon/elasticsearch-graphql#3] opened 2016-08-31 01:36 UTC
This project looks very useful. I am struggling to make valid queries on my /graphql endpoint. I populated Elastic Search with data from [their tutorial](https://www.elastic.co/guide/en/elasticsearch/reference/current/_exploring_your_data.html).

I understand that I need to compose a schema for the data in Elastic Search. I assume this is the same schema that is visible in the response from `//myElasticServer/indexName/typeName/_mapping`. Is this true? Or can you read the mapping and automatically generate the graphql structure without my error-prone code?

I think my questions could be solved if your example was more specific. Could you make a new example that exercises the data models of the introductory example from the ElasticSearch website?
- populates ES: https://www.elastic.co/guide/en/elasticsearch/reference/current/_exploring_your_data.html
- shows typical queries: http://graphql.org/docs/getting-started/

**Comment by nordsimon** [comment] 2016-08-31 04:31
Hi. Valid points, when i did this I simply assumed that users already would know elastic enough to understand but I see that this is not the case. I will make it a bit clearer on how to start from scratch

To answer your question, the json payload you get from _mapping is right. Initially I made the component fetch the mapping from the server but I changed that for several reasons like testing, mocking and allowing the project to run when you don't have access to the mapping.

**Comment by cyrfer** [comment] 2016-08-31 05:49
Thanks for the response. You're right that I am not very experienced with elastic.

I think I have the elastics 'mapping' schema specified correctly as I copied and pasted the direct parent object of the 'properties' object in the json response, like you showed in your example.

I must be failing to specify the 'hitSchema' correctly. I don't know where to begin for that. Actually, I was anticipating I would only need to provide the elastic mapping/schema as I thought the point of the project was to produce a graphql schema from the elastic mapping/schema.

**Comment by nordsimon** [comment] 2016-08-31 06:23
NP

Copy this https://github.com/nordsimon/elasticsearch-graphql-server-example/blob/master/schema.js and add as your hit schema. My reason for this is that I've been using elastic for searches but when I've resolved any ids I want to fetch them from their source db. Ex mongodb.

So by entering your custom hit schema you can then fetch the data from any source you want

This is actually the biggest reason I went to graphql. If you are only searching and fetching data from elastic and don't want to mix datasources then I would recommend you using elasticity query language alone

**Comment by nordsimon** [comment] 2016-08-31 06:27
Fora more complete example. Check out https://github.com/nordsimon/elasticsearch-graphql-server-example

That might help you

**Comment by cyrfer** [comment] 2016-08-31 06:35
Yes, I was using that for hitSchema. I changed it only when my queries were failing to produce valuable info. I would not be surprised if my queries are the issue. I had a breakpoint in the id's resolve function, but it never got hit for the requests I tried. I suspect I need to see an example query for the data populated in the elastic tutorial.

Thanks for explaining the custom hit schema. I will definitely need to leverage it and serve my responses from optimized sources.

Agreed. That is a great benefit of GraphQL. Great tips!

Yes, I have been modifying your complete example for my purposes.

**Comment by nordsimon** [comment] 2016-08-31 06:39
Okey, well this whole project is a little bit stall at the moment so it might not only be on your place. Could you send me the mapping json, then i can check it out locally

**Comment by cyrfer** [comment] 2016-08-31 17:13
I understand. It's looking great and I agree with the design decisions you mentioned above.

I suspect I need more experience with the GraphQL side of things. I will be experimenting more today. Your advice on a proper query format would be very helpful.

Here is the response from a ES `_mapping` call for the tutorial's data. I copied and pasted the value of the `account` key into your example code.

`GET {{elasticsearch}}/bank/account/_mapping`

``` json
{
  "bank": {
    "mappings": {
      "account": {
        "properties": {
          "account_number": {
            "type": "long"
          },
          "address": {
            "type": "string"
          },
          "age": {
            "type": "long"
          },
          "balance": {
            "type": "long"
          },
          "city": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "employer": {
            "type": "string"
          },
          "firstname": {
            "type": "string"
          },
          "gender": {
            "type": "string"
          },
          "lastname": {
            "type": "string"
          },
          "state": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

**Comment by nordsimon** [comment] 2016-08-31 18:20
Hi

Okey, the mapping can return from different base objects depending on which index you fetch it from, so I accept the mapping from the type base, which is account. Anyway if you copy paste this

```
var esGraphQL = require('elasticsearch-graphql')
var graphql = require('graphql')
var hitsSchema = require('./schema')

var graphqlHTTP = require('express-graphql')
var express = require('express')
var cors = require('cors')

var app = express()

var accountSearchSchema = esGraphQL({
  graphql: graphql,
  name: 'accountSearch',
  mapping: {
    "properties":{
      "account_number":{
        "type":"long"
      },
      "address":{
        "type":"string"
      },
      "age":{
        "type":"long"
      },
      "balance":{
        "type":"long"
      },
      "city":{
        "type":"string"
      },
      "email":{
        "type":"string"
      },
      "employer":{
        "type":"string"
      },
      "firstname":{
        "type":"string"
      },
      "gender":{
        "type":"string"
      },
      "lastname":{
        "type":"string"
      },
      "state":{
        "type":"string"
      }
    }
  },
  elastic: {
    host: 'http://localhost:9200',
    index: 'bank',
    type: 'account',
    query: function(query, context) {
      return query
    },
  },
  hitsSchema: hitsSchema
})

app.use(cors())

var graphqlMiddleware = graphqlHTTP(request => ({
  graphiql: true,
  schema: new graphql.GraphQLSchema({
    query: new graphql.GraphQLObjectType({
      name: 'RootQueryType',
      fields: {
        accountSearch: accountSearchSchema
      }
    })
  }),
  context: request
}))

app.use('/graphql', graphqlMiddleware);

app.listen(8100)
```

in server.js, then visit http://localhost:8100/graphql?query=%7B%0A%20%09accountSearch%20%7B%0A%09%09aggregations%20%7B%0A%20%20%20%20%20%20state%20%7B%0A%20%20%20%20%20%20%20%20terms%20%7B%0A%20%20%20%20%20%20%20%20%20%20value%0A%20%20%20%20%20%20%20%20%20%20count%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%20%20%20%20%0A%20%20%7D%20%0A%7D and you should be able to fetch an aggregation of all states in the data.

In the REPL you can inspect the entire schema and all values you can fetch

**Comment by nordsimon** [comment] 2016-08-31 18:32
Okey, so i inserted the sample data as you described andh the mapping and aggregations worked just fine togheter with my version of ES (2.3.4). This shouldn't matter very much. However I had some errors in the example hitsSchema so i fixed those and pushed to the repo so just git pull those. Here is a more extensive graphql query that shows more data that can be fetched

```
{
  accountSearch {
    aggregations {
      balance {
        stats {
          count
          min
          max
          avg
          sum
        }
      }
      gender {
        terms {
          value
          count
        }
      }
      state {
        terms {
          value
          count
        }
      }
    }
    totalHits
    hits {
      id
      index
      type
    }
  }
}
```

I should probably find some time to write a blog post describing all details of this, you are not the first one to wonder how, what and why

**Comment by cyrfer** [comment] 2016-08-31 21:10
Nice. Your code above is working for me now. Thank you.

I look forward to your blog post!

**Comment by nordsimon** [comment] 2016-09-01 05:25
Great. I will close this for now and find a better solution to introduce this tool. Thanks for taking time and commenting on this

**Closed as completed by nordsimon** 2016-09-01 05:25 UTC

**Comment by rishirajgarg** [comment] 2017-01-18 13:58
I tried all the steps exactly as explained in the above post but getting below error message. could you please help me to resolve .

      "message": "missing authentication token for REST request [/bank/account/_search]",


{
  "data": {
    "accountSearch": null
  },
  "errors": [
    {
      "message": "missing authentication token for REST request [/bank/account/_search]",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}

**Comment by rishirajgarg** [comment] 2017-01-18 14:36
Able to resolve the above issue by using     host: 'http://elastic:changeme@localhost:9200', in server.js

**Comment by rishirajgarg** [comment] 2017-01-18 14:39
but encountered another issue as below.
{
![bug](https://cloud.githubusercontent.com/assets/9433416/22068068/c5a31290-ddce-11e6-87e1-6fa741141c3b.png)
![bug2](https://cloud.githubusercontent.com/assets/9433416/22068119/eca0a75e-ddce-11e6-8804-6b6c6728b706.png)


  "data": {
    "accountSearch": null
  },
  "errors": [
    {
      "message": "all shards failed",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}

###########################
Elastic Search Logs

org.elasticsearch.transport.RemoteTransportException: [FSHl294][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: java.lang.IllegalArgumentException: Fielddata is disabled on text fields by default. Set fielddata=true on [state] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory.
        at org.elasticsearch.index.mapper.TextFieldMapper$TextFieldType.fielddataBuilder(TextFieldMapper.java:335) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.index.fielddata.IndexFieldDataService.getForField(IndexFieldDataService.java:111) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.config(ValuesSourceAggregationBuilder.java:355) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.resolveConfig(ValuesSourceAggregationBuilder.java:305) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:299) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:49) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.build(AbstractAggregationBuilder.java:126) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.build(AggregatorFactories.java:211) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:731) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:553) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:529) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:264) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:300) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:297) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.lambda$messageReceived$1(SecurityServerTransportInterceptor.java:208) ~[?:?]
        at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:109) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.lambda$messageReceived$2(SecurityServerTransportInterceptor.java:246) ~[?:?]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:53) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$null$0(ServerTransportFilter.java:136) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.maybeRun(AuthorizationUtils.java:131) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.setRunAsRoles(AuthorizationUtils.java:125) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.authorize(AuthorizationUtils.java:113) ~[?:?]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$inbound$1(ServerTransportFilter.java:138) ~[?:?]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:53) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$0(AuthenticationService.java:180) ~[x-pack-5.1.2.jar:5.1.2]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$lookForExistingAuthentication$2(AuthenticationService.java:199) ~[x-pack-5.1.2.jar:5.1.2]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lookForExistingAuthentication(AuthenticationService.java:211) [x-pack-5.1.2.jar:5.1.2]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.authenticateAsync(AuthenticationService.java:178) [x-pack-5.1.2.jar:5.1.2]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.access$000(AuthenticationService.java:140) [x-pack-5.1.2.jar:5.1.2]
        at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:112) [x-pack-5.1.2.jar:5.1.2]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.inbound(ServerTransportFilter.java:132) [x-pack-5.1.2.jar:5.1.2]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:253) [x-pack-5.1.2.jar:5.1.2]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:577) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:527) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.1.2.jar:5.1.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[2017-01-18T22:26:08,272][DEBUG][o.e.a.s.TransportSearchAction] [FSHl294] All shards failed for phase: [query]
org.elasticsearch.transport.RemoteTransportException: [FSHl294][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: java.lang.IllegalArgumentException: Fielddata is disabled on text fields by default. Set fielddata=true on [state] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory.
        at org.elasticsearch.index.mapper.TextFieldMapper$TextFieldType.fielddataBuilder(TextFieldMapper.java:335) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.index.fielddata.IndexFieldDataService.getForField(IndexFieldDataService.java:111) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.config(ValuesSourceAggregationBuilder.java:355) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.resolveConfig(ValuesSourceAggregationBuilder.java:305) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:299) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:49) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.build(AbstractAggregationBuilder.java:126) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.build(AggregatorFactories.java:211) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:731) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:553) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:529) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:264) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:300) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:297) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.lambda$messageReceived$1(SecurityServerTransportInterceptor.java:208) ~[?:?]
        at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:109) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.lambda$messageReceived$2(SecurityServerTransportInterceptor.java:246) ~[?:?]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:53) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$null$0(ServerTransportFilter.java:136) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.maybeRun(AuthorizationUtils.java:131) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.setRunAsRoles(AuthorizationUtils.java:125) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.authorize(AuthorizationUtils.java:113) ~[?:?]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$inbound$1(ServerTransportFilter.java:138) ~[?:?]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:53) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$0(AuthenticationService.java:180) ~[x-pack-5.1.2.jar:5.1.2]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$lookForExistingAuthentication$2(AuthenticationService.java:199) ~[x-pack-5.1.2.jar:5.1.2]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lookForExistingAuthentication(AuthenticationService.java:211) [x-pack-5.1.2.jar:5.1.2]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.authenticateAsync(AuthenticationService.java:178) [x-pack-5.1.2.jar:5.1.2]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.access$000(AuthenticationService.java:140) [x-pack-5.1.2.jar:5.1.2]
        at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:112) [x-pack-5.1.2.jar:5.1.2]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.inbound(ServerTransportFilter.java:132) [x-pack-5.1.2.jar:5.1.2]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:253) [x-pack-5.1.2.jar:5.1.2]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:577) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:527) [elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.1.2.jar:5.1.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
